version: "3.9"
services:
  api:
    command: gunicorn --bind 0.0.0.0:5000 app:app
    build: ./backEnd
    restart: on-failure
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    networks:
      - frontend
      - backend
  nginx:
    container_name: client
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: on-failure
    ports:
      - 80:80
    env_file:
      - ./.env.prod
    depends_on:
      - api
    networks:
      - frontend
  db:
    image: mongo:4.4
    env_file:
      - ./.env.prod
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
